#! /usr/bin/env python3

import optparse
import sys
import os
import json
import config

from typing import cast
from cli.logging import LogLevel

from comms import (
    ServerAuthResponseSuccess,
    handle_server_auth,
    server_auth,
    ServerAuthResponseFailure,
)
from cli.cli import main_loop


def parse_args() -> optparse.Values:
    opts = {}

    parser = optparse.OptionParser()
    parser.description = "Maliketh Operator Client"
    parser.usage = "usage: %prog --config OPERATOR_CONFIG_FILE [options]"
    parser.add_option(
        "-c",
        "--config",
        dest="config",
        default=None,
        help="The operator configuration file to use",
    )
    parser.add_option(
        "-d",
        "--debug",
        dest="debug",
        default=False,
        help="Enable debug mode",
        action="store_true",
    )
    opts, args = parser.parse_args()
    return opts


def validate_args(opts) -> None:
    if opts.config is None:
        print("You must specify a configuration file")
        sys.exit(1)

    # Check if config file exists
    if not os.path.exists(opts.config):
        print("Config file does not exist")
        sys.exit(1)

    # Check if config file is readable
    if not os.access(opts.config, os.R_OK):
        print("Config file is not readable")
        sys.exit(1)


def main():

    opts = parse_args()
    validate_args(opts)
    if opts.debug:
        config.log_level = LogLevel.DEBUG

    with open(opts.config, "r") as f:
        operator_config = config.OperatorConfig.from_json(f.read())

    # Authenticate to server
    auth_result = handle_server_auth(operator_config)
    operator_config.auth_token = auth_result

    # Subscribe to RabbitMQ queue

    # Go into main loop
    main_loop(operator_config)


if __name__ == "__main__":
    main()
