# This file contains the values of different routes for the operator listener.
# These will all be passed directly to @app.route() in Flask, so any valid Flask route
# arguments can be used here

# The base path for the operator routes
base_path: /op

# To get the full path for a route, the base path will be prepended to the path
stats:
  path: /stats
  methods:
    - GET

list_tasks:
  path: /tasks/list
  methods: 
    - GET

add_task:
  path: /tasks/add
  methods:
    - POST

task_results:
  path: /tasks/results/<task_id>
  methods: 
    - GET

delete_task:
  path: /tasks/delete/<task_id>
  methods:
    - DELETE

list_implants:
  path: /implant/list
  methods:
    - GET

kill_implant:
  path: /implant/kill/<implant_id>
  methods: 
    - DELETE

get_implant_config:
  path: /implant/config/<implant_id>
  methods:
    - GET

update_implant_config:
  path: /implant/config/<implant_id>
  methods:
    - POST

request_auth_token:
  path: /auth/token/request
  methods:
    - GET

revoke_auth_token:
  path: /auth/token/revoke
  methods:
    - GET

auth_token_status:
  path: /auth/token/status
  methods:
    - GET
