FROM python:3.11
ADD . /app
WORKDIR /app
ENV DEBUG=True
ENV PORT=5000
ENV BIND=0.0.0.0
ENV WORKERS=1
RUN pip install -r requirements.txt
#CMD python make_db.py && python app.py --start-operator -p ${PORT} ${DEBUG}
CMD gunicorn "app:operator_app" --bind ${BIND}:${PORT} --workers ${WORKERS} --reload
