FROM scratch
FROM python:3.11 as base
ADD ./server /app
ADD ./implant/ /implant
WORKDIR /app
ENV DEBUG=True
ENV PORT=5000
ENV BIND=0.0.0.0
ENV WORKERS=1
RUN pip install -r requirements.txt
RUN apt update
RUN apt install g++-mingw-w64 -y
#CMD python make_db.py && python app.py --start-operator -p ${PORT} ${DEBUG}

FROM base
CMD gunicorn "app:operator_app" --bind ${BIND}:${PORT} --workers ${WORKERS} --reload --timeout 120
