version: "3.2"
services:
  # Set up RabbitMQ
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq/
    networks:
        - rabbitmq_net

  postgres:
    image: postgres:13.3-alpine
    container_name: 'postgres'
    ports:
        - 5432:5432
    volumes:
        - db:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Vv4QZnP7eS#K7Z!4HWzx  # Change me!
        - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
        - rabbitmq_net

  # Start our Flask app
  flask:
    build: .
    container_name: 'flask'
    ports:
        - 443:443      # For implants
        - 28300:28300  # For operators
        - 4999:4999    # For development
    volumes:
        - .:/app
    depends_on:
        - rabbitmq
        - postgres
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge

volumes:
    rabbitmq_data:
    rabbitmq_log: 
    db:
        driver: local
