version: "3.2"
services:
  # Set up RabbitMQ
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq/
    networks:
        - rabbitmq_net

  # Start our Flask app
  flask:
    build: .
    container_name: 'flask'
    ports:
        - 443:443      # For implants
        - 28300:28300  # For operators
        - 5000:5000    # For development
    volumes:
        - .:/app
    depends_on:
        - rabbitmq

networks:
  rabbitmq_net:
    driver: bridge

volumes:
    rabbitmq_data:
    rabbitmq_log: 
